version: '3'

services:
  database:
    image: 'postgres'
    ports: 
      - '5436:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: wallet
    volumes: 
      - 'postgresql_data:/bitnami/postgresql'

volumes:
  postgresql_data:
    driver: local